version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: assignment_postgres
    restart: always
    environment:
      POSTGRES_USER: rohit
      POSTGRES_PASSWORD: rohitpassword
      POSTGRES_DB: assignment_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
